services:
  - type: web
    name: empath-eeg
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PORT
        value: 8000
      - key: WEB_CONCURRENCY
        value: 1
    healthCheckPath: /health
    healthCheckTimeout: 300 